name: Build Manager

on:
  watch:
    types: [started]

  workflow_dispatch:

jobs:
  build-manage:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./PermissionManager

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Write key
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo KEYSTORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' >> gradle.properties
            echo KEY_ALIAS='${{ secrets.KEY_ALIAS }}' >> gradle.properties
            echo KEY_PASSWORD='${{ secrets.KEY_PASSWORD }}' >> gradle.properties
            echo KEYSTORE_FILE='appKey.jks' >> gradle.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > appKey.jks
          fi
      
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean assembleRelease

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: PermissionManager
          path: PermissionManager/app/build/outputs/apk/release/*.apk

